# Generated by Django 4.0.1 on 2022-02-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/Blog/%Y/%m/%d'),
        ),
    ]
