# Generated by Django 4.0.1 on 2022-01-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_newsletter_alter_product_options_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
