# Generated by Django 4.0.1 on 2022-01-27 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0005_news_delete_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('email',), 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='email',
            field=models.EmailField(db_index=True, default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
